---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: install_chef_acceptance
    run_list:
      - recipe[test::chef_acceptance]
    attributes:
