name "git-gem"
maintainer "Patrick Wright"
maintainer_email "patrick@chef.io"
license "all_rights"
description "Installs/Configures git-gem-installer"
long_description "Installs/Configures git-gem-installer"
version "0.1.0"

depends "git"
depends "yum"
depends "apt"
